### ISSUE TITLE
Hyper-Express sometimes leaves request connections hanging

### ISSUE THREAD

**Issue by MichaelJCole** [kartikk221/hyper-express#42] opened 2021-12-29 20:38 UTC
Hi, I thought this was a LiveDirectory bug, but it happens even if I comment out the LiveDirectory code.

I am working on integrating passportjs with hyper-express based on the passportjs example I forked here:

https://github.com/MichaelJCole/hyper-express-sessions-passport-local

When I start the server and reload in chrome, almost always the server connections hangs on the '/' doc or some of the static assets.  If I reload 20ish times, the assets serve just fine.

To reproduce, try the master branch.  I'm using node 14.18.1.  Firefox 95.0.2.

![image](https://user-images.githubusercontent.com/1504790/147700841-c8236a42-9236-4f4d-9768-2b1668b13763.png)

Am I using this wrong?  Thank you!

**Comment by kartikk221** [comment] 2021-12-29 20:46
To build on my recommendation in the previously mentioned issue, this is likely an issue with one of your middlewares rather than LiveDirectory or any such package as requests hanging up means that the response is not being sent by the server which in your logic can only occur if one of the middlewares hold up the execution for some requests due to bad logic.

**Comment by MichaelJCole** [comment] 2021-12-29 21:22
Hi Kartik, thanks for the suggestion.  I made a small `min.js` file in that repo and can reproduce the error.

`rm -rf node_modules` fixes the issue.  

I am able to reproduce by starting multiple terminals with node `min.js`.  Subsequent instances do not say "port in use" they just start.  I can reproduce this even after rebooting.

The 2nd instance does not get a "port in use" error, and browser GET triggers console.log() in the 1st terminal.

Starting a 3rd, no error, and browser GET triggers 2nd terminal to console.log()

I'm using Ubuntu 20.04 WSL on Windows 10.  If I reboot Windows, I can reproduce the error.

If I try to start a different web server on the hyper-express port, I get an error.

If I try to start hyper-express on a port in use by another web server, I get an error.

Obviously, I don't need to run more than one instance on the same port - it is just surprising that 2 hyper-express will try to use the same port.

**Comment by kartikk221** [comment] 2021-12-30 15:29
This may be an underlying limitation of uWebsockets.js only being able to run on one port in a given environment but I do know that clustered workers/worker threads can run HyperExpress/uWebsockets.js instances on the same port for more performance. I would recommend you try and see if you can recreate this behavior in just uWebsockets.js to confirm that its a uWS limitation not a bug in HyperExpress.

**Comment by MichaelJCole** [comment] 2021-12-31 02:45
That uWS feature as the cause makes sense.  

Re: deleting node_modules, I agree with you in theory, but in practice there appeared to be some state in node_modules, or some meta-state about node_modules that deleting reset.   node-gyp and C++ node modules are outside my expertise, but claim to [compile executable artifacts at package install time](https://github.com/nodejs/node-gyp).  Anyways, it also surprised me.

**Comment by kartikk221** [comment] 2021-12-31 03:16
That is very odd, I guess you may be able to open an issue in the uWebsockets.js repository to get help there directly from the creator. I double checked the Server.listen() function and it is simply a wrapper of the uWS.TemplatedApp.listen() function so whatever behavior is causing this to occur is out of HyperExpress's control. I personally run multiple instances of the latest HyperExpress version on my development server on different ports and they all run fine so I am not sure why you are experiencing this issue. I'll go ahead and close this issue for now as it seems to be behavior specific to your setup and If is incorrect behavior then it has to be dealt with by the creator of uWebsockets.js. Feel free to post in this issue If you discover further information regarding this.

**Closed by kartikk221** 2021-12-31 03:16 UTC

**Comment by MichaelJCole** [comment] 2022-01-12 19:28
@kartikk221 here is an example of how to shutdown the uWS socket:  

https://github.com/uNetworking/uWebSockets.js/blob/master/examples/GracefulShutdown.js#L13

**Comment by kartikk221** [comment] 2022-01-12 19:32
> @kartikk221 here is an example of how to shutdown the uWS.js server:  
> 
> 
> 
> https://github.com/uNetworking/uWebSockets.js/blob/master/examples/GracefulShutdown.js#L13
> 
> 

Hi, this is already done by HyperExpress. See src/components/Server.js from lines 65 - 110.
