### ISSUE TITLE
Type issue after latest version

### ISSUE THREAD

**Issue by FifineHex** [kartikk221/hyper-express#201] opened 2023-11-14 14:52 UTC
after updating to the latest version 6.14.0 (I was using 6.12.0), all request and response types are any

![Captura de tela 2023-11-14 114944](https://github.com/kartikk221/hyper-express/assets/14141025/26f21cbe-46e1-4f8d-b492-12d3c69b0d00)
![Captura de tela 2023-11-14 115108](https://github.com/kartikk221/hyper-express/assets/14141025/1d7b1e2e-aa20-4bb2-8dd6-6c0f951adfde)

**Comment by kartikk221** [comment] 2023-11-14 16:02
Hi, seems like this bug was caused by Typescript not being able to do a union of `UserRouteHandler` and `MIddlewareHandler` in the spreadable arguments.

A fix for this bug has been pushed in the new `v6.14.1` version.

**Closed by kartikk221** 2023-11-14 16:02 UTC
